import random
import pyperclip
import pandas as pd

promts ={

                        "Place" : ['City', 'Forest', 'Beach', 'Desert', 'Mountains', 'Village', 'Island', 'Jungle', 'Ocean', 'Space', 'River', 'Castle', 'Farm', 'School', 'Museum', 'Temple', 'Factory', 'Mansion', 'Cave', 'Park', 'Library', 'Restaurant', 'Harbor', 'Stadium', 'Garden', 'Hospital', 'Office', 'Aquarium', 'Zoo', 'Airport', 'Station', 'Market', 'Theater', 'University', 'Cathedral', 'Volcano', 'Glacier', 'Prairie', 'Swamp', 'Valley', 'Canyon', 'Alley', 'Laboratory', 'Salon', 'Gym', 'Bakery', 'Plaza', 'Vineyard', 'Gallery', 'Rooftop'],                     
                        "Style" : ['Vintage', 'Modern', 'Rustic', 'Futuristic', 'Minimalist', 'Gothic', 'Baroque', 'Art Deco', 'Industrial', 'Bohemian', 'Surrealist', 'Abstract', 'Pop Art', 'Cubist', 'Expressionist', 'Impressionist', 'Steampunk', 'Retro', 'Mediterranean', 'Oriental', 'Nordic', 'Victorian', 'Bauhaus', 'Rococo', 'Classical', 'Byzantine', 'Avant-Garde', 'Tribal', 'Coastal', 'Shabby Chic', 'Eclectic', 'Zen', 'Art Nouveau', 'Contemporary', 'High-Tech', 'Organic', 'Psychedelic', 'Minimal', 'Traditional', 'Cyberpunk', 'Romantic', 'Fantasy', 'Realist', 'Geometric', 'Neoclassical', 'Graffiti', 'Opulent', 'Monochrome', 'Conceptual', 'Postmodern'],
                        "Resolution" : ['4K'],
                        "Subject" : ['Person', 'Cat', 'Dog', 'Alien', 'Fungoid', 'Robot', 'Bird', 'Fish', 'Dragon', 'Unicorn', 'Ghost', 'Vampire', 'Mermaid', 'Zombie', 'Dinosaur', 'Insect', 'Wizard', 'Witch', 'Fairy', 'Monster', 'Gnome', 'Elf', 'Tiger', 'Bear', 'Lion', 'Elephant', 'Horse', 'Wolf', 'Snake', 'Gorilla', 'Octopus', 'Butterfly', 'Angel', 'Demon', 'Tree Spirit', 'Cyclops', 'Yeti', 'Sphinx', 'Centaur', 'Griffin', 'Werewolf', 'Phoenix', 'Chimera', 'Troll', 'Kraken', 'Gargoyle', 'Minotaur', 'Leprechaun', 'Giant', 'Nymph'],
                        "Action" : ['Running', 'Jumping', 'Swimming', 'Dancing', 'Reading', 'Writing', 'Cooking', 'Painting', 'Singing', 'Playing (a musical instrument)', 'Hiking', 'Skiing', 'Fishing', 'Gardening', 'Building', 'Repairing', 'Teaching', 'Studying', 'Photographing', 'Drawing', 'Driving', 'Flying (a plane)', 'Sailing', 'Surfing', 'Climbing', 'Jogging', 'Cycling', 'Yoga', 'Meditating', 'Boxing', 'Wrestling', 'Shopping', 'Baking', 'Knitting', 'Crafting', 'Decorating', 'Programming', 'Gaming', 'Exploring', 'Traveling', 'Camping', 'Kayaking', 'Rowing', 'Skateboarding', 'Snowboarding', 'Scuba diving', 'Horseback riding', 'Archery', 'Fencing', 'Gymnastics'],
                        "TimeofDay" : ['Dawn', 'Morning', 'Noon', 'Afternoon', 'Evening', 'Dusk', 'Night', 'Midnight'],
                        "Weather" : ['Sunny', 'Cloudy', 'Rainy', 'Stormy', 'Snowy', 'Windy', 'Foggy', 'Overcast', 'Hail', 'Sleet', 'Thunderstorm', 'Hot', 'Cold', 'Humid', 'Dry', 'Blizzard', 'Heatwave', 'Frost', 'Drizzle', 'Mist'],
                        "Mood" : ['Happy', 'Sad', 'Angry', 'Relaxed', 'Excited', 'Nervous', 'Tired', 'Bored', 'Confident', 'Anxious', 'Hopeful', 'Frustrated', 'Content', 'Curious', 'Melancholic', 'Surprised', 'Fearful', 'Romantic', 'Peaceful', 'Reflective'],
                        "ColorScheme" : ['Monochrome', 'Pastel', 'Vibrant', 'Earth Tones', 'Neon', 'Primary Colors', 'Secondary Colors', 'Complementary', 'Analogous', 'Triadic', 'Cool Colors', 'Warm Colors', 'Black and White', 'Metallic', 'Autumn Shades', 'Spring Hues', 'Summer Palette', 'Winter Colors', 'Sunset Colors', 'Oceanic Tones', 'Jewel Tones', 'Retro Palette', 'Minimalist', 'Sepia', 'Grayscale', 'Rainbow', 'Tropical', 'Nordic Colors', 'Desert Palette', 'Vintage', 'Muted', 'Bold and Bright', 'Dark and Moody', 'Pastel Neon', 'Shades of Green', 'Blue Hues', 'Red Variants', 'Golden and Bronze', 'Silver and Gray', 'Pastel Earth Tones', 'Citrus Colors', 'Berry Tones', 'Night Sky Palette', 'Sunrise Colors', 'Forest Colors', 'Urban Colors', 'Candy Colors', 'Rustic Palette', 'Galactic Tones', 'Bohemian Colors'],
                        "Era" : ['Stone Age', 'Bronze Age', 'Iron Age', 'Ancient Egypt', 'Classical Greece', 'Roman Empire', 'Medieval', 'Renaissance', 'Enlightenment', 'Industrial Revolution', 'Victorian Era', 'Edwardian Era', 'Roaring Twenties', 'Great Depression', 'World War II', 'Post-War Era', 'Cold War', 'Space Age', 'Digital Age', 'Future (Speculative)', 'Cyberpunk Era', 'Prehistoric', 'Elizabethan Era', 'Baroque Period', 'Age of Exploration', 'Gilded Age', 'Jazz Age', 'Atomic Age', 'Hippie Movement', 'Disco Era', 'Information Age', 'Regency Era', 'Ming Dynasty', 'Edo Period (Japan)', 'Ottoman Empire', 'Viking Age', 'Byzantine Empire', 'Aztec Empire', 'Inca Empire', 'Colonial America', 'American Civil War', 'Belle Époque', 'Ancient Mesopotamia', 'Mughal Era', 'Age of Sail', 'Wild West', 'Progressive Era', 'Ancient India', 'Soviet Era', 'Interwar Period'],
                        "Texture" : ['Smooth', 'Rough', 'Glossy', 'Matte', 'Silky', 'Velvety', 'Fuzzy', 'Grainy', 'Textured', 'Metallic', 'Wooden', 'Glassy', 'Leathery', 'Sandy', 'Stony', 'Bumpy', 'Ribbed', 'Knitted', 'Woven', 'Polished', 'Embossed', 'Crinkled', 'Fluffy', 'Prickly', 'Slimy', 'Wet', 'Dry', 'Sticky', 'Slippery', 'Hard', 'Soft', 'Spongy', 'Rugged', 'Sharp', 'Crumbly', 'Squishy', 'Chalky', 'Pitted', 'Burnished', 'Rustic', 'Sheer', 'Oily', 'Shaggy', 'Sparkling', 'Plush', 'Perforated', 'Meshed', 'Marbled', 'Filmy', 'Padded'],
                        "Lighting" : ['Bright', 'Dim', 'Natural', 'Artificial', 'Fluorescent', 'Incandescent', 'LED', 'Candlelight', 'Neon', 'Ambient', 'Spotlight', 'Backlit', 'Side-lit', 'Overhead', 'Diffused', 'Harsh', 'Soft', 'Warm', 'Cool', 'Colored', 'Flickering', 'Reflective', 'Glowing', 'Shadowy', 'Sunset', 'Sunrise', 'Moonlit', 'Starlight', 'Strobe', 'Twinkling', 'Underwater', 'Firelight', 'Indirect', 'Flash', 'Ultraviolet', 'Blacklight', 'Dappled', 'Hazy', 'Foggy', 'Golden Hour', 'Blue Hour', 'Studio', 'Stage', 'Disco', 'Laser', 'Fairy Lights', 'Streetlight', 'Lantern', 'Spotlight', 'Emergency Lights'],
                        "Perspective" : ['Eye-Level', 'High Angle', 'Low Angle', 'Birds-Eye View', 'Worms-Eye View', 'Dutch Angle/Tilt', 'Over-the-Shoulder', 'Point-of-View (POV)', 'Close-Up', 'Extreme Close-Up', 'Medium Shot', 'Long Shot', 'Wide Shot', 'Establishing Shot', 'Two-Shot', 'Three-Shot', 'Overhead Shot', 'Aerial Shot', 'Panoramic Shot', 'Tracking Shot', 'Dolly Shot', 'Crane Shot', 'Tilt Shot', 'Zoom', 'Whip Pan', 'Reverse Angle', 'Reaction Shot', 'Cutaway', 'Cross-Shot', 'Rack Focus', 'Depth of Field Shot', 'Soft Focus', 'Split Screen', 'Freeze Frame', 'Time-Lapse', 'Slow Motion', 'Steadicam Shot', 'Handheld Shot', 'Fish-Eye Lens', 'Macro Shot', 'Mirror Shot', 'Subjective Shot', 'Objective Shot', 'Silhouette Shot', 'Shadow Shot', 'Low-Key Lighting Shot', 'High-Key Lighting Shot', 'Natural Light Shot', 'Artificial Light Shot', 'Composite Shot'],
                        "Material" : ['Wood', 'Metal', 'Glass', 'Stone', 'Fabric', 'Plastic', 'Paper', 'Leather', 'Fur', 'Silk', 'Velvet', 'Denim', 'Cotton', 'Wool', 'Linen', 'Lace', 'Satin', 'Rubber', 'Gold', 'Silver', 'Copper', 'Bronze', 'Marble', 'Granite', 'Crystal', 'Clay', 'Ceramic', 'Porcelain', 'Brick', 'Concrete', 'Water', 'Ice', 'Sand', 'Diamond', 'Pearl', 'Gemstone', 'Carbon Fiber', 'Neon', 'Foam', 'Sponge', 'Resin', 'Acrylic', 'Graphite', 'Obsidian', 'Coral', 'Amber', 'Ivory', 'Bamboo', 'Feather', 'Shell'],
                        "BackgroundElements" : ['Trees', 'Mountains', 'Buildings', 'Skyline', 'Clouds', 'River', 'Ocean', 'Beach', 'Forest', 'Street', 'Park', 'Bridge', 'Flowers', 'Grass', 'Rocks', 'Hills', 'Vehicles', 'Animals', 'People', 'Statues', 'Fences', 'Pathway', 'Garden', 'Waterfall', 'Lake', 'Moon', 'Stars', 'Sun', 'Planets', 'Space', 'Cityscape', 'Road', 'Signs', 'Furniture', 'Artwork', 'Lights', 'Windows', 'Doors', 'Balcony', 'Stairs', 'Path', 'Alley', 'Courtyard', 'Fountain', 'Playground', 'Farm', 'Field', 'Vineyard', 'Ruins', 'Horizon'],
                        "ForegroundElements" : ['Character', 'Animal', 'Plant', 'Vehicle', 'Furniture', 'Rock', 'Tree', 'Flower', 'Water Body (e.g., pond, fountain)', 'Sculpture', 'Signpost', 'Pathway', 'Fence', 'Tool', 'Book', 'Food', 'Drink', 'Computer', 'Phone', 'Camera', 'Musical Instrument', 'Art Supplies', 'Map', 'Backpack', 'Clothing Item', 'Footwear', 'Jewelry', 'Watch', 'Glasses', 'Hat', 'Umbrella', 'Lantern', 'Candle', 'Fire (e.g., campfire, fireplace)', 'Ball (e.g., soccer ball, basketball)', 'Toy', 'Pet', 'Basket', 'Pillow', 'Blanket', 'Bag', 'Suitcase', 'Bicycle', 'Skateboard', 'Surfboard', 'Snowboard', 'Ski', 'Binoculars', 'Telescope', 'Painting/Photograph'],
                        "AdditionalCharacters" : ['Astronaut', 'Knight', 'Wizard', 'Scientist', 'Detective', 'Pirate', 'Robot', 'Superhero', 'Villain', 'King', 'Queen', 'Elf', 'Fairy', 'Mermaid', 'Vampire', 'Zombie', 'Ninja', 'Samurai', 'Warrior', 'Alien', 'Angel', 'Demon', 'Chef', 'Musician', 'Artist', 'Dancer', 'Athlete', 'Doctor', 'Nurse', 'Teacher', 'Farmer', 'Carpenter', 'Mechanic', 'Police Officer', 'Firefighter', 'Spy', 'Pilot', 'Sailor', 'Explorer', 'Adventurer', 'Businessperson', 'Student', 'Monk', 'Priest', 'Witch', 'Cowboy/Cowgirl', 'Gladiator', 'Ranger', 'Bard', 'Inventor'],
                        "Accessory" : ['Sunglasses', 'Hat', 'Scarf', 'Necklace', 'Earrings', 'Bracelet', 'Watch', 'Ring', 'Belt', 'Bag', 'Backpack', 'Umbrella', 'Gloves', 'Hairpin', 'Tiara', 'Mask', 'Headphones', 'Camera', 'Binoculars', 'Wand', 'Sword', 'Shield', 'Bow and Arrow', 'Magic Staff', 'Lantern', 'Book', 'Map', 'Flask', 'Telescope', 'Musical Instrument', 'Paintbrush', 'Sketchpad', 'Laptop', 'Tablet', 'Smartphone', 'Game Controller', 'Skateboard', 'Bicycle', 'Surfboard', 'Ball (e.g., basketball, soccer ball)', 'Fishing Rod', 'Binoculars', 'Magnifying Glass', 'Compass', 'Flashlight', 'Keychain', 'Wallet', 'Makeup', 'Perfume Bottle', 'Pet (like a small dog or cat)'],
                        "CulturalInfluence" : ['Victorian', 'Byzantine', 'Ottoman', 'Aztec', 'Edo Japanese', 'Ancient Egyptian', 'Roman', 'Ancient Greek', 'Norse', 'Aboriginal', 'Zulu', 'Maori', 'Inuit', 'Celtic', 'Mayan', 'Persian', 'Han Chinese', 'Mongolian', 'Renaissance European', 'Indigenous Amazonian', 'Mughal', 'Polynesian', 'Ancient Sumerian', 'Medieval Arab', 'Viking', 'Ancient Indian', 'Apache', 'Sioux', 'Navajo', 'Incan', 'Italian Renaissance', 'Babylonian', 'Russian Tsarist', 'French Baroque', 'Spanish Colonial', 'Ottoman Turkish', 'Ancient Khmer', 'African Tribal', 'Southeast Asian', 'Indigenous Andean', 'Korean Joseon Dynasty', 'British Colonial', 'Ancient Mesopotamian', 'Pre-Columbian', 'Germanic Tribal', 'Ancient Celtic', 'Ming Dynasty Chinese', 'Caribbean Islander', 'Scandinavian Modern', 'Balkan'],
                        "TechnologyLevel" : ['Stone Age', 'Bronze Age', 'Iron Age', 'Medieval', 'Renaissance', 'Industrial', 'Victorian', 'World War II Era', 'Modern', 'Cybernetic', 'Virtual Reality', 'Spacefaring', 'Interstellar', 'Nanotech', 'Steampunk', 'Diesel Punk', 'Biotech', 'Neolithic', 'Classical Antiquity', 'Middle Ages', 'Enlightenment', 'Pre-Industrial', 'Early Industrial', 'Atomic Age', 'Cold War Tech', 'Information Age', 'Post-Information', 'Quantum Computing', 'Fusion Power', 'Antigravity', 'Artificial Intelligence', 'Cyberpunk', 'Augmented Reality', 'Genetic Engineering', 'Post-Apocalyptic', 'Hypersonic', 'Alternate Energy', 'Smart Materials', 'Biomechanical', 'Holographic', 'Virtual Immersion', 'Time Travel Capable', 'Terraforming', 'Intergalactic', 'Dark Energy Utilization', 'Superconducting', 'Magnetic Levitation', 'Quantum Teleportation', 'Post-Singularity', 'Alien Technology'],
                        "FantasyElements" : ['Dragons', 'Magic', 'Elves', 'Dwarves', 'Orcs', 'Wizards', 'Sorcerers', 'Enchanted Forests', 'Alchemy', 'Enchanted Weapons', 'Runes', 'Elemental Powers', 'Goblins', 'Fairies', 'Witches', 'Vampires', 'Werewolves', 'Giants', 'Griffins', 'Phoenixes', 'Centaurs', 'Unicorns', 'Merfolk', 'Necromancy', 'Portals to Other Worlds', 'Chimeras', 'Spellcasting', 'Crystal Magic', 'Divine Intervention', 'Shapeshifters', 'Summoning', 'Telepathy', 'Enchanted Artifacts', 'Familiars', 'Curses', 'Holy Quests', 'Prophecies', 'Dark Lords', 'Sacred Groves', 'Mystical Relics', 'Ley Lines', 'Spirit Realms', 'Magical Creatures', 'Forbidden Spells', 'Arcane Libraries', 'Alchemical Transmutation', 'Mythical Beasts', 'Legendary Swords', 'Ancient Runestones', 'Sorcery Academies'],
                        "HistoricalPeriod" : ['Stone Age', 'Ancient Egypt', 'Classical Greece', 'Roman Empire', 'Dark Ages', 'Viking Age', 'Middle Ages', 'Renaissance', 'Age of Discovery', 'Elizabethan Era', 'Baroque Period', 'Enlightenment', 'American Revolution', 'Industrial Revolution', 'Victorian Era', 'Belle Époque', 'World War I', 'Roaring Twenties', 'Great Depression', 'World War II', 'Cold War', 'Space Age', 'Information Age', 'Digital Revolution', 'Future Dystopian', 'Future Utopian', 'Pre-Columbian Americas', 'Colonial Era', 'Napoleonic Wars', 'The Gilded Age', 'The Jazz Age', 'The Atomic Age', 'The Civil Rights Movement', 'The Internet Age', 'The Bronze Age', 'The Iron Age', 'Ancient Mesopotamia', 'The Crusades', 'The Ottoman Empire', 'The Ming Dynasty', 'The Edo Period', 'The Meiji Restoration', 'The Progressive Era', 'The Interwar Period', 'The Postwar Era', 'The Age of Terrorism', 'The Quantum Age', 'The Regency Period', 'The Silk Road Era', 'The Cybernetic Age'],
                        "ArchitecturalStyle" : ['Gothic', 'Baroque', 'Victorian', 'Art Deco', 'Modernist', 'Brutalist', 'Bauhaus', 'Colonial', 'Tudor', 'Byzantine', 'Romanesque', 'Neoclassical', 'Greek Revival', 'Renaissance', 'Federal', 'Queen Anne', 'Craftsman', 'Prairie', 'Art Nouveau', 'International', 'Postmodern', 'Mediterranean Revival', 'Gothic Revival', 'Georgian', 'Industrial', 'Mission Revival', 'Streamline Moderne', 'Tudor Revival', 'Italianate', 'Dutch Colonial', 'Spanish Colonial', 'Pueblo Revival', 'Cape Cod', 'Ranch', 'Mid-Century Modern', 'Victorian Revival', 'Shingle Style', 'Contemporary', 'French Provincial', 'Châteauesque', 'Colonial Revival', 'Greek Revival', 'Federal Revival', 'Richardsonian Romanesque', 'Sullivanesque', 'Colonial Spanish', 'Neo-Gothic', 'Art Moderne', 'Neo-Eclectic', 'Post-Modern Revival', 'Futuristic Sci-Fi', 'Cyberpunk', 'Steampunk', 'Space Station', 'Underwater City', 'Floating Island', 'Castle in the Sky', 'Alien Hive', 'Crystal Palace', 'Treehouse City', 'Subterranean Cavern', 'Lunar Base', 'Martian Colony', 'Time-Traveling Observatory', 'Haunted Mansion', 'Wizards Tower', 'Magical Castle', 'Floating City', 'Cloud City', 'Ice Palace', 'Mushroom Kingdom', 'Elven Tree City', 'Dystopian Megacity', 'Post-Apocalyptic Ruins', 'Bioengineered Habitat', 'Coral Reef City', 'Arcology', 'Biosphere Settlement', 'Steam-Powered Factory', 'Gothic Cathedral Spaceship'],
                        "Season" : ['Spring', 'Summer', 'Autumn', 'Winter', 'Rainy', 'Dry', 'Monsoon', 'Pre-Winter', 'Post-Monsoon', 'Harvest', 'Blossom', 'Frosty', 'Chilly', 'Hot', 'Stormy', 'Sunny', 'Misty', 'Windy', 'Snowy', 'Foggy', 'Hazy', 'Overcast', 'Tropical', 'Polar', 'Equatorial', 'Mediterranean', 'Continental', 'Desert', 'Coastal', 'Mountainous', 'Arctic', 'Subarctic', 'Tundra', 'Savanna', 'Grassland', 'Rainforest', 'Taiga', 'Highland', 'Lowland', 'Steppe', 'Alpine', 'Forest', 'Wetland', 'Island', 'Plateau', 'Archipelago', 'Volcanic', 'Coral Reef', 'Oasis', 'Canyon'],
                        "ClothingStyle" : ['Casual', 'Formal', 'Sportswear', 'Vintage', 'Bohemian', 'Punk', 'Business Casual', 'Couture', 'Streetwear', 'Preppy', 'Hipster', 'Retro', 'Gothic', 'Hip Hop', 'Grunge', 'Minimalist', 'Edgy', 'Elegant', 'Classic', 'Urban', 'Chic', 'Avant-Garde', 'Rockabilly', 'Western', 'Tomboy', 'Romantic', 'Mod', 'Hippy', 'Military', 'Artsy', 'Geeky', 'Cybergoth', 'Steampunk', 'Vintage-Inspired', 'Glamorous', 'Rugged', 'Eclectic', 'Futuristic', 'Retro-Futurism', 'Boho-Chic', 'Nomadic', 'Exotic', 'Tribal', 'Nautical', 'Safari', 'Normcore', 'Techwear', 'Sustainable', 'Arts and Crafts', 'Victorian-Inspired'],
                        "Emotion" : ['Joyful', 'Sadness', 'Anger', 'Surprise', 'Disgust', 'Fear', 'Trust', 'Anticipation', 'Love', 'Remorse', 'Excitement', 'Gratitude', 'Contentment', 'Hopeful', 'Confident', 'Curious', 'Relaxed', 'Anxious', 'Lonely', 'Envious', 'Proud', 'Guilty', 'Amazed', 'Bored', 'Sympathetic', 'Nostalgic', 'Empathetic', 'Irritated', 'Overwhelmed', 'Playful', 'Awed', 'Jealous', 'Regretful', 'Amused', 'Disappointed', 'Melancholic', 'Frustrated', 'Cautious', 'Rejected', 'Shy', 'Confused', 'Devastated', 'Satisfied', 'Determined', 'Grumpy', 'Indifferent', 'Surly', 'Optimistic', 'Pensive', 'Peaceful'],
                        "Theme" : ['Adventure', 'Mystery', 'Fantasy', 'Sci-Fi', 'Romance', 'Horror', 'Steampunk', 'Cyberpunk', 'Fairy Tale', 'Mythology', 'Space Exploration', 'Underwater World', 'Post-Apocalyptic', 'Historical', 'Futuristic', 'Magical', 'Time Travel', 'Urban Jungle', 'Wilderness', 'Surreal', 'Whimsical', 'Dreamlike', 'Noir', 'Dystopian', 'Utopian', 'Supernatural', 'Mythical Creatures', 'Alien Worlds', 'Enchanted Forest', 'Parallel Universe', 'Gothic', 'Retro', 'Industrial', 'Natural Wonders', 'Celestial', 'Tropical Paradise', 'Cityscape', 'Subterranean', 'Extraterrestrial', 'Ancient Ruins', 'Steampunk Fantasy', 'Cyberpunk Noir', 'Fairytale Castle', 'Time-Traveling Adventure', 'Magical Realism', 'Post-Apocalyptic Dystopia', 'Galactic Exploration', 'Mythical Beasts', 'Futuristic City', 'Lost World Discovery'],
                        "Genre" : ['Fantasy', 'Science Fiction', 'Mystery', 'Romance', 'Horror', 'Adventure', 'Historical Fiction', 'Thriller', 'Crime', 'Comedy', 'Drama', 'Action', 'Fairy Tale', 'Mythology', 'Superhero', 'Western', 'Cyberpunk', 'Steampunk', 'Dystopian', 'Post-Apocalyptic', 'Space Opera', 'Time Travel', 'Alternate History', 'Gothic', 'Slice of Life', 'Surreal', 'Magical Realism', 'Satire', 'Epic', 'Noir', 'Romantic Comedy', 'Coming of Age', 'Family', 'War', 'Musical', 'Fantasy Adventure', 'Sci-Fi Thriller', 'Historical Romance', 'Psychological Drama', 'Crime Mystery', 'Space Exploration', 'Cyberpunk Noir', 'Supernatural Horror', 'Action-Adventure', 'Mythological Fantasy', 'Post-Apocalyptic Dystopia', 'Fairy Tale Romance', 'Mystery Comedy', 'Steampunk Adventure', 'Romantic Fantasy'],
                        "Rarity" : ['Common', 'Uncommon', 'Rare', 'Epic', 'Legendary', 'Mythical', 'Exotic', 'Ultra-Rare', 'Limited Edition', 'One-of-a-Kind', 'Scarce', 'Precious', 'Unique', 'Antique', 'Vintage', 'Obscure', 'Secret', 'Hidden', 'Mysterious', 'Elusive', 'Fabled', 'Enigmatic', 'Ancient', 'Extraterrestrial', 'Timeless', 'Ethereal', 'Majestic', 'Cosmic', 'Supernatural', 'Transcendent', 'Divine', 'Mystical', 'Enchanted', 'Rarefied', 'Incomparable', 'Priceless', 'Invaluable', 'Peerless', 'Singular', 'Unearthly', 'Otherworldly', 'Celestial', 'Rare Gem', 'Collectors Item', 'Treasured', 'Priceless Artifact', 'Legendary Relic', 'One-of-a-Kind Masterpiece', 'Lost Treasure', 'Hidden Gem'],

                        }

selected_items = {category: random.choice(items) for category, items in promts.items()}

final = str(selected_items)

# Copying the message to clipboard
pyperclip.copy(final)
print("Message copied to clipboard. You can now paste it.")